### PR TITLE
WIP: Update to latest structopt

### LINKED ISSUE #17: Update to structopt 0.3
`structopt` had released v0.3.0 a month ago. This update brings in a number of breaking changes (most noticeably `raw` attributes removal), cosmetic changes (like span-based error reporting), and a lot of minor improvements and bug fixes. Furthermore, it has been improving further over this month, working both on new features and bug fixes. Also docs have been clarified and greatly improved. 

Summarizing all of it, I propose to use `structopt` v0.3 as `clap_derive`.

### PR DESCRIPTION
**Pull request by CreepySkeleton**
Fixes #17 
This is import of [structopt](https://github.com/TeXitoi/structopt/) v0.3 crate.

This is purely work-in-progress, the job now is to make all the necessary changes to adapt this to `clap` 0.3.

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
Hm, it seems certain commits are missing. Interesting...

**Comment by CreepySkeleton** [comment]
OK guys, sorry for the radio silence, I got caught up in other projects and this had mostly been blocked on https://github.com/TeXitoi/structopt/pull/278 . I'll get to the work tomorrow, now I'm going to take a short break and play video games :)

**Comment by pksunkara** [comment]
What! You just replaced this package with structopt.

**Comment by CreepySkeleton** [comment]
@pksunkara Yes, this is the intention. Now I'm going to rework it a bit so it has the same API as `clap_derive` but implements all the features from `structopt v0.3`.

And no, I didn't forget about it, I just got lost in other stuff (and nobody tried to ping me anyway). I'll finish the work in a week or so.

**Comment by pksunkara** [comment]
I will review it once this is ready. Even though I can't merge it.

**Comment by pksunkara** [comment]
Looking at this, it looks like the rebase wasn't done properly. If we resolve the conflicts every commit (since there are only 25, it should be simple), then we don't need to make it this complex. Can you tell me the commits where structopt is completely in clap?

**Comment by CreepySkeleton** [comment]
> looking at this, it looks like the rebase wasn't done properly. If we resolve the conflicts every commit (since there are only 25, it should be simple), then we don't need to make it this complex.

I was thinking the same, initially, but I changed my mind. Now it's about 100 extra commits, the difference it pretty damn huge (`structopt` has evolved a lot since then) so I really feel like one big patch would be much simpler than 100 not-so-big patches.

> since there are only 25

He-he-he, take a closer look 😄 


>  Can you tell me the commits where structopt is completely in clap?

Could you please elaborate? I don't get what you mean.

**Comment by pksunkara** [comment]
> Could you please elaborate? I don't get what you mean.

If I want to start porting structopt changes to clap, from which commit in structopt should I start?

**Comment by pksunkara** [comment]
https://github.com/TeXitoi/structopt/commit/30da80cb809d3505a306a9cd0796dfd0d90ec3f0 is the answer to my question.

**Comment by CreepySkeleton** [comment]
> If I want to start porting structopt changes to clap, from which commit in structopt should I start?

This is pretty useless question if you ask me. You don't really need to know the branching point, leave that for git to figure out!

This is how I did it:
```sh
git clone https://github.com/clap-rs/clap_derive
cd clap_derive

git remote add --mirror=fetch structopt https://github.com/TeXitoi/structopt/
git fetch structopt master
git co FETCH_HEAD
git rebase master
# resolve a LOT of merge conflicts ...
git co -b update_to_latest_structopt
```

**Comment by pksunkara** [comment]
I am almost done porting the changes from structopt. Will make a PR soon.

**Comment by CreepySkeleton** [comment]
Closing in favor of #23

**Pull request closed without merging**
